# Generated by Django 3.1.1 on 2020-09-27 15:00

import core.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import eopp.validations
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The skill name.', max_length=254)),
                ('description', models.CharField(blank=True, help_text='Description of the skill.', max_length=254)),
                ('quantity_description', models.CharField(blank=True, help_text='Description of the skill quantity (e.g. unit).', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The machine name.', max_length=254, unique=True)),
                ('manufacturer', models.CharField(blank=True, help_text='Manufacturer of the machine.', max_length=254)),
                ('description', models.CharField(blank=True, help_text='Description of the machine e.g. machine type.', max_length=254)),
                ('build_space_x', models.PositiveIntegerField(default=0, help_text='Build space in x-axis in mm.', validators=[django.core.validators.MinValueValidator(0)])),
                ('build_space_y', models.PositiveIntegerField(default=0, help_text='Build space in y-axis in mm.', validators=[django.core.validators.MinValueValidator(0)])),
                ('build_space_z', models.PositiveIntegerField(default=0, help_text='Build space in z-axis in mm.', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part', models.FileField(help_text='The uploaded 3d part.', upload_to=core.models.model_upload_path, validators=[eopp.validations.validate_file_extension_3dpart])),
                ('is_valid', models.BooleanField(default=False, editable=False, help_text='Is the 3d part valid (a closed/watertight 3d part).')),
                ('volume', models.FloatField(blank=True, editable=False, help_text='Volume of the part.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('bounding_box_x', models.FloatField(blank=True, editable=False, help_text='Length (x-axis) of the bounding box of the part.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('bounding_box_y', models.FloatField(blank=True, editable=False, help_text='Width (y-axis) of the bounding box of the part.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('bounding_box_z', models.FloatField(blank=True, editable=False, help_text='Height (z-axis) of the bounding box of the part.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_costs', models.PositiveIntegerField(default=0, help_text='The costs to use the skill for one unit of the skill specific quantity.', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Skill', to='core.machine')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Skill', to='core.abstractskill')),
            ],
            options={
                'ordering': ['machine'],
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='skills',
            field=models.ManyToManyField(help_text='Skills of the machine.', related_name='Machines', through='core.Skill', to='core.AbstractSkill'),
        ),
    ]
