# Generated by Django 3.1.1 on 2020-09-27 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='machine',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='Skill', to='core.machine'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='Skill', to='core.abstractskill'),
        ),
    ]
