# Generated by Django 3.1.1 on 2020-12-10 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillconsumable',
            old_name='quantity',
            new_name='variable_quantity',
        ),
        migrations.AddField(
            model_name='skillconsumable',
            name='fixed_quantity',
            field=models.FloatField(default=0, help_text='The quantity required in the consumable unit to use the skill.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
