# Generated by Django 3.1.1 on 2020-09-27 15:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200927_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_costs', models.PositiveIntegerField(default=0, help_text='The costs to use the skill for one unit of the skill specific quantity.', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AppliedSkill', to='core.machine')),
            ],
            options={
                'ordering': ['machine'],
            },
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='quantity_costs',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill',
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.CharField(blank=True, help_text='Description of the skill.', max_length=254),
        ),
        migrations.AddField(
            model_name='skill',
            name='name',
            field=models.CharField(default=1, help_text='The skill name.', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='quantity_description',
            field=models.CharField(blank=True, help_text='Description of the skill quantity (e.g. unit).', max_length=254),
        ),
        migrations.DeleteModel(
            name='AbstractSkill',
        ),
        migrations.AddField(
            model_name='appliedskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AppliedSkill', to='core.skill'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='skills',
            field=models.ManyToManyField(help_text='Skills of the machine.', related_name='Machines', through='core.AppliedSkill', to='core.Skill'),
        ),
    ]
