# Generated by Django 3.1.1 on 2020-10-26 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201026_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='unit',
        ),
    ]
