# Generated by Django 3.1.1 on 2021-01-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201210_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='data_type',
            field=models.CharField(choices=[('String', str), ('Boolean', bool), ('Integer', int), ('Float', float)], default='String', help_text='The data type of the value.', max_length=50),
        ),
        migrations.AlterField(
            model_name='constraint',
            name='operator',
            field=models.CharField(choices=[('=', '='), ('!=', '!='), ('<', '<'), ('>', '>'), ('>=', '>='), ('<=', '<=')], default='=', help_text='Has the result to be equal, smaller, or bigger then this value.', max_length=50),
        ),
    ]
