# Generated by Django 3.1.1 on 2020-10-27 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_skill_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ability',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Abilities'},
        ),
        migrations.AlterModelOptions(
            name='constraint',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='partmanufacturingprocessstep',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='skillconsumable',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='skillconsumable',
            name='quantity_co2',
            field=models.PositiveIntegerField(default=0, help_text='The CO2-e for one unit of this consumable.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='skillconsumable',
            name='quantity_price',
            field=models.PositiveIntegerField(default=0, help_text='The costs in € for one unit of this consumable.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
