# Generated by Django 3.1.1 on 2020-10-28 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201027_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='co2_importance',
            field=models.IntegerField(default=1, help_text='The importance (weight) of the co2 for the evaluation of the solutions.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='part',
            name='price_importance',
            field=models.IntegerField(default=1, help_text='The importance (weight) of the price for the evaluation of the solutions.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='part',
            name='time_importance',
            field=models.IntegerField(default=1, help_text='The importance (weight) of the time for the evaluation of the solutions.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
