# Generated by Django 3.1.1 on 2021-01-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210120_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='data_type',
            field=models.CharField(choices=[('str', 'String'), ('bool', 'Boolean'), ('int', 'Integer'), ('float', 'Float')], default='str', help_text='The data type of the value.', max_length=50),
        ),
    ]
