# Generated by Django 3.1.1 on 2021-01-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210120_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='data_type',
            field=models.CharField(choices=[('str', 'str'), ('bool', 'bool'), ('int', 'int'), ('float', 'float')], default='str', help_text='The data type of the value.', max_length=50),
        ),
    ]
