# Generated by Django 3.1.1 on 2021-01-20 21:10

from django.db import migrations, models
import eopp.validations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210120_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='value',
            field=models.CharField(help_text='Value of the specific requirement describing how much this requirement can be fulfilled. Please see the description and unit of the selected requirement for information.', max_length=254, validators=[eopp.validations.validate_data_type_of_value]),
        ),
    ]
