# Generated by Django 3.1.1 on 2020-11-13 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201112_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillconsumable',
            name='description',
            field=models.CharField(blank=True, help_text='Specific description of the used consumable.', max_length=254),
        ),
        migrations.AlterField(
            model_name='part',
            name='evaluation_method',
            field=models.IntegerField(default=3, help_text='The evaluation method. 1: Ranking regarding single field values (e.g. price). The highest importance weight is considered first. 2: Ranking regarding normalized and weighted criteria (price, time and co2). 3: Ranking using the CRITIC method. The importance weights are not considered.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
