# Generated by Django 3.1.1 on 2020-11-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201113_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='description',
            field=models.CharField(blank=True, help_text='Specific description of the ability.', max_length=254),
        ),
        migrations.AddField(
            model_name='constraint',
            name='description',
            field=models.CharField(blank=True, help_text='Specific description of the constraint.', max_length=254),
        ),
    ]
