# Generated by Django 3.1.1 on 2020-11-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201113_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='description',
            field=models.CharField(blank=True, help_text='Specific description of the requirement.', max_length=254),
        ),
    ]
