# Generated by Django 3.1.1 on 2020-11-18 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_requirement_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillconsumable',
            name='fixed_co2',
            field=models.PositiveIntegerField(default=0, help_text='The fixed CO2-e for this consumable.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='skillconsumable',
            name='fixed_price',
            field=models.PositiveIntegerField(default=0, help_text='The fixed costs in € for this consumable.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='skillconsumable',
            name='variable_co2',
            field=models.PositiveIntegerField(default=0, help_text='The variable CO2-e for one unit of this consumable.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='skillconsumable',
            name='variable_price',
            field=models.PositiveIntegerField(default=0, help_text='The variable costs in € for one unit of this consumable.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
