# Generated by Django 3.1.1 on 2021-04-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumablecost',
            name='co2',
            field=models.FloatField(default=0, help_text='The CO2-eq. for this consumable.'),
        ),
        migrations.AlterField(
            model_name='permutation',
            name='co2',
            field=models.FloatField(default=0, help_text='The overall CO2-eq. to manufacture the part.'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='co2',
            field=models.FloatField(default=0, help_text='The overall CO2-eq. to manufacture the part.'),
        ),
    ]
