# Generated by Django 3.1.1 on 2020-10-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permutation',
            name='consumables',
            field=models.ManyToManyField(help_text='Overall required consumables for this permutation.', related_name='Permutation', to='solutions.ConsumableCost'),
        ),
    ]
