# Generated by Django 3.1.1 on 2020-10-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_auto_20201027_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permutation',
            name='consumables',
            field=models.ManyToManyField(blank=True, help_text='Overall required consumables for this permutation.', related_name='Permutation', to='solutions.ConsumableCost'),
        ),
        migrations.AlterField(
            model_name='permutation',
            name='solution',
            field=models.ManyToManyField(blank=True, help_text='The resource skill for one part manufacturing process step.', related_name='Permutation', to='solutions.Solution'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='consumables',
            field=models.ManyToManyField(blank=True, help_text='Required consumables for this permutation.', related_name='Solution', to='solutions.ConsumableCost'),
        ),
        migrations.AlterField(
            model_name='solutionspace',
            name='permutations',
            field=models.ManyToManyField(blank=True, help_text='All permutations for this solution space.', related_name='SolutionSpace', to='solutions.Permutation'),
        ),
    ]
