# Generated by Django 3.1.1 on 2020-10-27 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0003_auto_20201027_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permutation',
            old_name='solution',
            new_name='solutions',
        ),
    ]
