# Generated by Django 3.1.1 on 2020-10-28 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201027_2041'),
        ('solutions', '0005_auto_20201028_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='part_manufacturing_process_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Solution', to='core.partmanufacturingprocessstep'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='resource_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Solution', to='core.resourceskill'),
        ),
    ]
