# Generated by Django 3.1.1 on 2020-10-28 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0006_auto_20201028_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='The required quantity in the skill unit to manufacture the part.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
