# Generated by Django 3.1.1 on 2020-10-28 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0007_solution_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permutation',
            name='is_optimal',
        ),
        migrations.AddField(
            model_name='permutation',
            name='rank',
            field=models.PositiveIntegerField(default=0, help_text='The rank of this permutation after evaluation.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
