# Generated by Django 3.1.1 on 2020-10-28 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0008_auto_20201028_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permutation',
            options={'ordering': ['rank']},
        ),
    ]
