# Generated by Django 3.1.1 on 2020-10-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0009_auto_20201028_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permutation',
            options={'ordering': ('-created_at', 'rank')},
        ),
    ]
