# Generated by Django 3.1.1 on 2020-10-28 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0010_auto_20201028_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permutation',
            options={'ordering': ('-rank', '-created_at')},
        ),
    ]
