# Generated by Django 3.1.1 on 2020-11-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0012_auto_20201028_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='permutation',
            name='comparison_value',
            field=models.PositiveIntegerField(blank=True, help_text='The comparison value of this permutation.', null=True),
        ),
    ]
