# Generated by Django 3.1.1 on 2020-11-12 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0013_permutation_comparison_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumablecost',
            name='time',
            field=models.PositiveIntegerField(default=0, help_text='The time in s for this consumable.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
